package utils

import "fmt"

//write code for stack data structure storing generic types
// generated by chatgpt

type Stack struct {
	items []any
}

func MakeStack() Stack {
	return Stack{make([]any, 0)}
}

func (s *Stack) Push(item any) {
	s.items = append(s.items, item)
}

func (s *Stack) Pop() any {
	if len(s.items) == 0 {
		return nil
	}
	item := s.items[len(s.items)-1]
	s.items = s.items[:len(s.items)-1]
	return item
}
func (s *Stack) Peek() any {
	if len(s.items) == 0 {
		return nil
	}
	return s.items[len(s.items)-1]
}

func (s *Stack) Get(i int) any {
	if len(s.items) == 0 {
		return nil
	}
	return s.items[i]
}

func (s *Stack) Len() int {
	return len(s.items)
}

func (s *Stack) IsEmpty() bool {
	return len(s.items) == 0
}

func (s *Stack) GetStack() []any {
	return s.items
}

func (s *Stack) PrintStack() bool {
	fmt.Println("---------")
	for i := len(s.items) - 1; i >= 0; i-- {
		fmt.Println(s.items[i])
	}
	fmt.Println("---------")
	return true
}